project:
  type: book

book:
  title: "R from Beginner to Advanced"
  author: "Francisco J. Navarro"
  date: "16/9/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - standards.qmd
        - objects.qmd
        - types.qmd   
        - packages.qmd
    - part: "Part 1: Data Manipulation"
      chapters: 
        - manipulation.qmd
        - plyrdplyr.qmd
        - tidy.qmd
        - random.qmd
        - databases.qmd
    - part: "Part 2: Programming in R"
      chapters:
        - habits.qmd
        - logic.qmd
        - functions.qmd
        - debugging.qmd
        - profiling.qmd
    - part: "Part 3: Statistics in R"
      chapters:
        - descriptive.qmd
        - exploratory.qmd
        - inferential.qmd
        - regression.qmd
    - part: "Part 4: Graphics"
      chapters: 
        - graphs.qmd
    - part: "Part 5: Data Products"
      chapters: 
        - products.qmd
        - reproducible.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

