project:
  type: book
  
book:
  title: "R for Research in Action"
  author: "Francisco J. Navarro"
  date: "10/13/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro_objects.qmd
        - intro_types.qmd   
        - intro_packages.qmd
        - intro_style.qmd
    - part: "Part 1: Manipulating Data"
      chapters: 
        - manipu_reading.qmd
        - manipu_writing.qmd
        - manipu_tidydata.qmd
        - manipu_transforming.qmd
        - manipu_subsetting.qmd
        - manipu_plyrdplyr.qmd
        - manipu_date.qmd
        - manipu_text.qmd
        - manipu_databases.qmd
    - part: "Part 2: Statistics in R"
      chapters:
        - stats_descriptive.qmd
        - stats_exploratory.qmd
        - stats_inferential.qmd
        - stats_regression.qmd
    - part: "Part 3: Programming in R"
      chapters:
        - program_habits.qmd
        - program_logic.qmd
        - program_functions.qmd
        - program_iteration.qmd
        - program_debugging.qmd
        - program_profiling.qmd
    - part: "Part 4: Graphics"
      chapters: 
        - graphs.qmd
        - graph_ggplot.qmd
        - graph_types.qmd
    - part: "Part 5: Modeling"
      chapters: 
        - model_flow.qmd
        - model_spend.qmd
        - model_fit.qmd
        - model_random.qmd
    - part: "Part 6: Time Series"
      chapters: 
        - time_analysis.qmd
        - time_objects.qmd
        - time_components.qmd
        - time_decomposition.qmd
        - time_seasonality.qmd
        - time_correlation.qmd
        - time_forecast_workflow.qmd
        - time_forecast_regression.qmd
        - time_forecast_ma.qmd
        - time_forecast_smooth.qmd
        - time_forecast_arima.qmd
        - time_forecast_ml.qmd
    - part: "Part 7: Data Products"
      chapters: 
        - products.qmd
        - product_repro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt # problema w/ hmtlwidgets en products.qmd > Interactivity

editor: visual

