project:
  type: book

book:
  title: "R in Action: From Beginner to Advanced"
  author: "Francisco J. Navarro"
  date: "09/17/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - objects.qmd
        - types.qmd   
        - packages.qmd
        - style.qmd
    - part: "Part 1: Manipulating Data"
      chapters: 
        - manipulation.qmd
        - subsetting.qmd
        - missing.qmd
        - date.qmd
        - plyrdplyr.qmd
        - tidyverse.qmd
        - tidy.qmd
        - databases.qmd
    - part: "Part 2: Programming in R"
      chapters:
        - habits.qmd
        - logic.qmd
        - functions.qmd
        - debugging.qmd
        - profiling.qmd
    - part: "Part 3: Statistics in R"
      chapters:
        - descriptive.qmd
        - exploratory.qmd
        - inferential.qmd
        - regression.qmd
    - part: "Part 4: Graphics"
      chapters: 
        - graphs.qmd
        - ggplot.qmd
        - typesofgraphs.qmd
    - part: "Part 5: Modeling"
      chapters: 
        - random.qmd
    - part: "Part 6: Data Products"
      chapters: 
        - products.qmd
        - reproducible.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

