project:
  type: book

book:
  title: "R for Research in Action"
  author: "Francisco J. Navarro"
  date: "09/26/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - objects.qmd
        - types.qmd   
        - packages.qmd
        - style.qmd
    - part: "Part 1: Manipulating Data"
      chapters: 
        - reading.qmd
        - writing.qmd
        - tidydata.qmd
        - transforming.qmd
        - subsetting.qmd
        - plyrdplyr.qmd
        - date.qmd
        - databases.qmd
    - part: "Part 2: Statistics in R"
      chapters:
        - descriptive.qmd
        - exploratory.qmd
        - inferential.qmd
        - regression.qmd
    - part: "Part 3: Programming in R"
      chapters:
        - habits.qmd
        - logic.qmd
        - functions.qmd
        - iteration.qmd
        - debugging.qmd
        - profiling.qmd
    - part: "Part 4: Graphics"
      chapters: 
        - graphs.qmd
        - ggplot.qmd
        - typesofgraphs.qmd
    - part: "Part 5: Modeling"
      chapters: 
        - spending.qmd
        - fitting.qmd
        - random.qmd
    - part: "Part 6: Data Products"
      chapters: 
        - products.qmd
        - reproducible.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt # problem w/ hmtlwidgets en products.qmd > Interactivity
editor: visual

